# time that oh-my-zsh is loaded.
#ZSH_THEME="jonathan"
#ZSH_THEME="frisk"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

#plugins=(scala git gradle docker common-aliases zsh-autosuggestions)

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"
fpath=(~/.zsh/completion $fpath)
autoload -U compinit
compinit

alias zcon="vim ~/.zshrc"
alias szcon="source ~/.zshrc"
alias vrc="vim ~/.vimrc"
alias svrc="source ~/.vimrc"
alias copy="xsel --clipboard"
alias xclip="xclip -selection c"

alias port="sudo netstat -nlp"
alias desk="cd /home/kevino/.local/share/applications"

alias jcli="/home/kevino/programs/wildfly-10.0.0.Final/bin/jboss-cli.sh --connect"
alias jst="vim /home/kevino/programs/wildfly-10.0.0.Final/standalone/configuration/standalone.xml"

if command -v tmux>/dev/null; then
  [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
fi

bindkey -v
bindkey '^Xh' _complete_help
bindkey jj vi-cmd-mode

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "$terminfo[kcuu1]" up-line-or-beginning-search
bindkey "$terminfo[kcud1]" down-line-or-beginning-search

#source $HOME/.bash_aliases

declare -a dirs_to_prepend

DISABLE_AUTO_TITLE=true

source ~/projects/dotfiles/zsh/git_prompt.zsh
source ~/projects/dotfiles/zsh/alias.zsh
source ~/projects/dotfiles/zsh/history.zsh
source ~/projects/dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
#source ~/projects/dotfiles/zsh/theme.zsh
