fpath=(~/.zsh/completion $fpath)
autoload -U compinit
compinit

if command -v tmux>/dev/null; then
  [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && exec tmux
fi

export SUDO_EDITOR=vi

# enable Vi mode
bindkey -v
bindkey '^Xh' _complete_help
bindkey jj vi-cmd-mode

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "$terminfo[kcuu1]" up-line-or-beginning-search
bindkey "$terminfo[kcud1]" down-line-or-beginning-search

declare -a dirs_to_prepend

source ~/projects/dotfiles/zsh/clock.zsh
source ~/projects/dotfiles/zsh/kube_ctx.zsh
source ~/projects/dotfiles/zsh/git_prompt.zsh
source ~/projects/dotfiles/zsh/alias.zsh
source ~/projects/dotfiles/zsh/history.zsh
source ~/projects/dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/projects/dotfiles/zsh/theme.zsh

#SDKMAN
export SDKMAN_DIR="/home/kevino/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

export PATH=$PATH:~/bin
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/usr/local/kubebuilder/bin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/.local/bin

zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

if [ $commands[kubectl] ]; then
    source <(kubectl completion zsh)
    alias k=kubectl
    complete -o default -F __start_kubectl k
fi

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /home/kevino/bin/vault vault
